server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启sentinel功能
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城-购物车模块-接口文档"
    pacakage: com.hmall.cart.controller
    des: "黑马商城-购物车模块-接口文档"
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true #是否设置请求方式作为资源名称